Improve seqs requests with errors
Duet3D/PanelDueFirmware pull request #108
Opened 2021-05-17 07:37 UTC by mfs12

Closes #80

2021-05-17 07:39 UTC, mfs12 commented
Hey @wilriker  @dc42, i went a little crazy with refactoring. I hope you like the outcome. Perhaps it makes sense to bring it in with another request separated from this issue. As this issue is then fixed with one line commit.

Please leave your feedback. Thanks.

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> -	if (seqs.updateNetwork)
In this method an optimized fetch-order was maintained because there are a few internal dependencies. I cannot see this order anymore after your change.

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> -#else
The `ShowLine` macro has been *very* useful in the past diagnosing issues because it will show you the last line reached before the control self-resets due to e.g. illegal memory access. I'd rather not remove it (same goes for all removed lines below).

2021-05-17 09:30 UTC, wilriker commented on src/UI/UserInterface.cpp
> -		Reconnect();
Internal data state should be forcefully reset if the user requests reset of the mainboard. How do you handle this now or why do you think it is no longer necessary?

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> +	for (i = current - seqs; i < ARRAY_SIZE(seqs); i++)
Please preferably use `++i` over `i++` unless you need `i++` specifically.

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> +	ReceivedDataEvent currentResponseType = currentSeq != nullptr ? currentSeq->event : ReceivedDataEvent::rcvUnknown;
Why are you updating `currentResponseType` here again? Are there cases where you get here but not into `ProcessReceivedValue`?

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> -			MessageLog::AppendMessage("Connected");
Why did you remove this message?

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> -		newStatus = OM::PrinterStatus::panelInitializing;
Where do you set the Panel to this state now instead?

2021-05-17 09:30 UTC, wilriker commented on src/PanelDue.cpp
> -	SerialIo::Sendf("M409 F\"d99f\"\n");		// Get initial status
I am undecided if removing this will have any negative side-effect. Same goes for removing this line from `Reconnect()`.

2021-05-17 09:38 UTC, mfs12 commented on src/Hardware/SerialIo.cpp
> +						cbs->ParserErrorEncountered(lastState, fieldId.c_str(), fieldVal.c_str(), arrayIndices); // Notify the consumer that we ran into an error
my bad. lastState is now always updated, not only in debug builds.

2021-05-17 09:39 UTC, mfs12 commented on src/PanelDue.cpp
> +	{ .event = rcvOMKeyBoards, .seqid = rcvSeqsBoards, .lastSeq = 0, .state = SeqStateInit, .key = "boards", .flags = "v" },
exactly, there's now an init state, where they are all updated.

2021-05-17 09:44 UTC, mfs12 commented on src/PanelDue.cpp
> +	for (i = current - seqs; i < ARRAY_SIZE(seqs); i++)
what is exactly the difference? I never got this 100% ;)

Sure i can change that.

2021-05-17 09:50 UTC, mfs12 commented on src/PanelDue.cpp
> +	for (i = current - seqs; i < ARRAY_SIZE(seqs); i++)
fixed.

2021-05-17 09:52 UTC, wilriker commented on src/UI/UserInterface.cpp
> -		Reconnect();
M999 is terminal on RRF. It will not reply anything anymore. And since we know that because the user requested it, I'd prefer to keep the internal reset in PanelDue here as well - why wait for something when we already know it's going to happen? And it does not overcomplicate the code either IMHO.

2021-05-17 09:53 UTC, mfs12 commented on src/PanelDue.cpp
> -			MessageLog::AppendMessage("Connected");
It didn't feel relevant enough to me. As the status is displayed always in the top right corner.

You want it back?

2021-05-17 09:54 UTC, wilriker commented on src/PanelDue.cpp
> +	for (i = current - seqs; i < ARRAY_SIZE(seqs); i++)
`i++` does effectively the following
```
int temp = i;
i = i + 1;
return i
```
whereas `++i` only does
```
i = i + 1;
return i;
```
so you save saving a value that you do not use anyway.

2021-05-17 09:56 UTC, wilriker commented on src/PanelDue.cpp
> -			MessageLog::AppendMessage("Connected");
It's not important just wanted to get your reasons.

2021-05-17 10:07 UTC, mfs12 commented on src/PanelDue.cpp
> -		newStatus = OM::PrinterStatus::panelInitializing;
It's not used anymore. I think it's basically the same as connecting. I think is it's also problematic to mix printer states and panel states. This violates modularisation and creates a new class of problems.

You want it back. To me it looks fines... it shows... Connecting -> standby or idle or halted as soon there's a valid state received.

2021-05-17 10:22 UTC, mfs12 commented on src/PanelDue.cpp
> -	SerialIo::Sendf("M409 F\"d99f\"\n");		// Get initial status
This happens now in the main loop same as it did before. It usually run into printerPollTimeout which is not optimal, i agree on that. I have another look into this.

2021-05-17 10:32 UTC, wilriker commented on src/PanelDue.cpp
> -	SerialIo::Sendf("M409 F\"d99f\"\n");		// Get initial status
But that makes for an empty first loop run because probably no one can touch anything that has not yet been initialized, nothing to repaint. But yes, it will only stall for a few milliseconds until it starts updating. So fine for me.

2021-05-17 10:33 UTC, wilriker commented on src/PanelDue.cpp
> -		newStatus = OM::PrinterStatus::panelInitializing;
Maybe this is no longer required after I changed the code to ignore poll interval while initializing. Before it had shown "Connecting" for multiple seconds while it was obviously already connected because it received data. Also "Connecting" already is a Panel state so "Initializing" was just one more. But it can be unifired.

2021-05-17 13:57 UTC, mfs12 commented on src/UI/UserInterface.cpp
> -		Reconnect();
The reconnect introduces circular dependency between PanelDue and UserInterface which is something which should be avoided. And you don't know it really does reset until it's reset. At this state you assume it will reset. And you know it when it's done.

But I will revert it.

2021-05-17 14:04 UTC, mfs12 commented on src/PanelDue.cpp
> +	ReceivedDataEvent currentResponseType = currentSeq != nullptr ? currentSeq->event : ReceivedDataEvent::rcvUnknown;
Because currentResponseType is not anymore a global variable. There's now only one pointer to the right seq-entry which is called currentSeq from which you then derive currentResponseType in case you need it. I think this could be refactored in future as well to simplify the code further.

2021-05-17 14:06 UTC, mfs12 commented on src/PanelDue.cpp
> -		newStatus = OM::PrinterStatus::panelInitializing;
Well it shows connecting as long as no valid state is received. Which is ok i think. I consider this as resolved.

2021-05-17 14:09 UTC, mfs12 commented on src/PanelDue.cpp
> -#else
I didn't think of that because when i enabled it i just saw flickering in the top corner with barely any use to me. But add it again.

2021-05-17 14:11 UTC, mfs12 commented on src/PanelDue.cpp
> -	if (seqs.updateNetwork)
Is this documented somewhere? In the Object Model or what kind of "internal dependency" is it?

2021-05-17 14:15 UTC, mfs12 commented on src/PanelDue.cpp
> -	if (seqs.updateNetwork)
I even already thought about if it makes sense to change the order of seqs by interest. I fix this.

2021-05-17 14:20 UTC, mfs12 commented on src/PanelDue.cpp
> -	if (seqs.updateNetwork)
fixed.

2021-05-17 14:32 UTC, mfs12 commented on src/PanelDue.cpp
> -#else
Added it again. But left the entries out for now. I think they will come back as needed.

2021-05-17 14:32 UTC, wilriker commented on src/PanelDue.cpp
> +#elif (DEBUG == 2)
You still need to restore all the existing lines using it.

2021-05-17 15:02 UTC, mfs12 commented on src/PanelDue.cpp
> +#elif (DEBUG == 2)
done.

2021-05-17 15:08 UTC, mfs12 commented on src/UI/UserInterface.cpp
> -		Reconnect();
@wilriker i added it and tested it and without it it "feels" nicer more consistent. Could you test it and provide you opinion, please.

2021-05-18 13:05 UTC, wilriker commented on src/UI/UserInterface.cpp
> -		Reconnect();
I tested it and I agree that it's actually better without that call to `Reconnect()`.

2021-05-18 13:12 UTC, wilriker commented
Testing your branch resulted in a bug that both my bed heater and my tool head showed the same temperatures (both the value of the bed thermistor). Please investigate what could cause this.

2021-05-18 13:15 UTC, wilriker requested changes
Testing your branch resulted in a bug that both my bed heater and my tool head showed the same temperatures (both the value of the bed thermistor). Please investigate what could cause this.

2021-05-19 05:47 UTC, mfs12 commented
> Testing your branch resulted in a bug that both my bed heater and my tool head showed the same temperatures (both the value of the bed thermistor). Please investigate what could cause this.

Having a decent look into it. I can see the data arrives properly. The function UI::UpdateCurrentTemperature is called properly and then i loose track. Something goes wrong accessing the right heaterSlots. But i don't really understand what should happen. So would be cool if you could have a look into that. BTW no changes were done to UI::UpdateCurrentTemperature.

2021-05-19 07:55 UTC, wilriker commented
I did `git bisect` it and here's the result:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
ae6ddd6aa890473de9f21adeb8c700dd6c12bca6
dd535f34d5f14cbc4ae24cc2d1c287ddedc5c8d8
We cannot bisect more!
```
The `ae6ddd6` did not show any values so I could not test this. Therefore there are two of them. If I find some more time later, I will try to look more deeply into what might be the problem here but my gut feeling says it's got something to do with:
```
diff --git a/src/PanelDue.cpp b/src/PanelDue.cpp
index ecad60a..07e5b21 100755
--- a/src/PanelDue.cpp
+++ b/src/PanelDue.cpp
@@ -1248,25 +1248,23 @@
 // Public functions called by the SerialIo module
 static void ProcessReceivedValue(StringRef id, const char data[], const size_t indices[])
 {
-	if (StringStartsWith(id.c_str(), "result"))
+	if (StringStartsWith(id.c_str(), "result:"))
 	{
```

2021-05-19 14:10 UTC, wilriker requested changes

2021-05-19 14:10 UTC, wilriker commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
I don't see the usefulness of knowing (statefully) what you last requested. Can you please elaborate on this?

2021-05-19 14:10 UTC, wilriker commented on src/PanelDue.cpp
> +			id.Prepend(currentReqSeq->key);
This needs to be
```
currentRespSeq->key
```

2021-05-19 14:10 UTC, wilriker commented on src/PanelDue.cpp
> +		dbg("seq %s %d DONE", currentReqSeq->key, currentReqSeq->state);
Why are you outputting the state of `currentReqSeq` here instead of `currentRespSeq`?

2021-05-19 14:18 UTC, mfs12 commented on src/PanelDue.cpp
> +			id.Prepend(currentReqSeq->key);
fixed.

2021-05-19 14:19 UTC, mfs12 commented on src/PanelDue.cpp
> +		dbg("seq %s %d DONE", currentReqSeq->key, currentReqSeq->state);
removed obsoleted debugging. fixed.

2021-05-19 14:22 UTC, mfs12 commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
it isn't last request, but the current. It points to the seq last request. It's an interator and gives us context to easily check if a proper response arrived.

2021-05-19 14:26 UTC, wilriker commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
AFAICT you nowhere check if `currentReqSeq` and `currentRespSeq` do match. BTW in terms of terminology using `seq` is misleading. `seqs` are the sequence numbers for the ObjectModel *keys* so using something like `currentReqKey` and `currentRespKey` makes much more sense (sorry that I missed that before).

2021-05-19 14:46 UTC, mfs12 commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
Well, the last patch introduced comparing reqseq and respseq when a "key" is processed.

And about the naming, the name is inherited from the old infrastructure. So i would like to stick with it for now. There's more refactoring upcoming. Please. ;)

2021-05-19 14:49 UTC, wilriker commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
To be the wise-guy here: the old code used `currentResponseType`. No "seq" in there. :-P

Will review your latest patch tomorrow.

2021-05-19 14:54 UTC, mfs12 commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
Well but it head before different data type and just containing an enumeration. Now it's a pointer pointing to an entry in an array which was called before and now "seqs". So who is the wise guy now ;)

2021-05-20 08:55 UTC, wilriker commented on src/PanelDue.cpp
> +			// no seq request was sent or invalid response
Sorry, but again: don't do that, do NOT expect that your request and response match. Ever. Send out requests and identify whatever the answer is. There are certain cases where PanelDue sends request after request to RRF but RRF is busy and will only reply (in bulk) at a later time. Sending requests from PanelDue towards RRF is more like a wishlist - most of the time it will grant you your wishes but every now and then you will get something different, unexpected.

2021-05-20 09:20 UTC, mfs12 commented on src/PanelDue.cpp
> +			// no seq request was sent or invalid response
This happens when i try to be smarten than i am. :)

Fixed it. Please check and merge... if possible.

2021-05-20 11:18 UTC, wilriker commented on src/PanelDue.cpp
> +			MessageLog::AppendMessageF("Error in response %s", currentRespSeq->key);
When you get here, that's not a parsing error but an expected out-of-buffers-reply. That is an expected and acceptable behavior and should only lead to retrying this request. This happens e.g. if contending requests from DWC and PanelDue are hitting hard on the available resources of RRF (mainly in Duet 2 boards). Only notify the user in case of parsing errors in the appropriate method (as already done).

2021-05-20 11:19 UTC, wilriker commented on src/PanelDue.cpp
> +			// no seq request was sent or invalid response
We all start in a project, trying to improve things not knowing all possible limitations or restrictions. You'll grow into that I'm sure. ;-)

2021-05-20 11:22 UTC, wilriker commented on src/PanelDue.cpp
> +static struct Seq *currentReqSeq = nullptr;
TBH I am still not happy with the variable names because they are misleading (a _sequence number_ belongs to a *key* and before your changes the `seqs` struct only saved the sequence numbers and a reload-flag one each per key). But I am going to stop arguing about that here.

2021-05-20 11:46 UTC, mfs12 commented on src/PanelDue.cpp
> +			MessageLog::AppendMessageF("Error in response %s", currentRespSeq->key);
reverted.

2021-05-20 11:48 UTC, merged