Fix normal polling interval
Duet3D/PanelDueFirmware pull request #124
Opened 2021-06-10 10:42 UTC by mfs12

Closes #122

2021-06-10 13:57 UTC, wilriker requested changes

2021-06-10 15:39 UTC, mfs12 commented on src/PanelDue.cpp
> +							SerialIo::Sendf("M409 F\"d99f\"\n");
why was then oktosend not directly implemented down in the RequestTimer module?

2021-06-10 15:43 UTC, mfs12 commented on src/PanelDue.cpp
> +							SerialIo::Sendf("M409 F\"d99f\"\n");
Also check the comment above OkToSend

```
8 // Return true if sending a command or file list request to the printer now is a good idea.
     7 // We don't want to send these when the printer is busy with a previous command, because they will        block normal status 
     
     ```

2021-06-10 15:50 UTC, mfs12 reviewed
The idea behind this refactoring is to create a understandable solution. The one before was in my opinion unmaintainable without staring and debugging for hours. The code got way simpler. I think also the ratelimiting can be implemented in easier ways.

In my opinion what makes this code so unmaintainable is that uses everywhere global variables, each cluttering and used all over this huge module. This way it isn't easy understandable, it's really hard to debug and understand the flow and relations of data.

Instead of trying to recreate the "old" behavior it would make sense to specify the wanted behavior and then implement a simple solution.

Let's refactor it, make it better, make it maintainable and open for new features and other developers.

2021-06-10 15:50 UTC, mfs12 commented on src/PanelDue.cpp
> +					lastPollTime = SystemTick::GetTickCount();
Well this is not necessary anymore. check the flow.

2021-06-15 08:09 UTC, wilriker commented on src/PanelDue.cpp
> +							SerialIo::Sendf("M409 F\"d99f\"\n");
I cannot tell you why it was implemented where it is. But its purpose was to limit low-priority requests to situations where a tight status-update-rate was not required (e.g. when being idle as opposed to running a job). Status-updates are always considered normal priority (while user input can be considered high-priority).

2021-06-15 08:13 UTC, wilriker commented
> Instead of trying to recreate the "old" behavior it would make sense to specify the wanted behavior and then implement a simple solution.

I don't mind improving code maintainability. But this must not come with regressions.

The wanted behavior is simple: status updates as often as possible while maintaining a stable response rate. That's why it starts at a 0.5s interval and decreases this interval slowly when it encounters that RRF was too often unable to actually reply (most likely because PanelDue is contending for resources with a parallel running DWC). Low-prio requests (as file list updates) should  be limited to certain statuses as they are already. Status-updates should always be performed. User input needs to be sent when the user presses a button. While screensaver is active, poll-rate can be reduced significantly because updates will not be rendered anyway but we still need status-polls because the response might contain reasons to wake the screen up (apart from the user touching it).

2021-06-15 17:42 UTC, mfs12 commented on src/PanelDue.cpp
> +							SerialIo::Sendf("M409 F\"d99f\"\n");
hm... more and more questions arise. well i think i reverted the behavior to the old one.

But still this think is confusing. I added a table of status to #122. Could adapt the comment with as much information as possible.

And fetching filelists is usually done on user request, right? So it's high prio. So it should happen always no matter what the status is. Can you provide also some examples for high, normal and low prio requests to get a better feeling about that topic.

2021-06-15 17:44 UTC, mfs12 commented on src/PanelDue.cpp
> +							SerialIo::Sendf("M409 F\"d99f\"\n");
Perhaps also move further discussion to the issue and get this thing merged.

2021-06-15 18:07 UTC, mfs12 commented
> I don't mind improving code maintainability. But this must not come with regressions.

Sometimes it is not clear what regression is... ;)

2021-06-16 11:00 UTC, mfs12 commented
@wilriker so things should be fine now. Are you as well?

2021-06-17 07:42 UTC, merged